<%@ Page Title="ProtuctTypes" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProductTypes.aspx.cs" Inherits="WebApplication.ProductTypes.ProductTypes" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ProtuctTypesGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ProtuctTypesGridView_RowCancelingEdit"
            OnRowDeleting="ProtuctTypesGridView_RowDeleting"
            OnRowEditing="ProtuctTypesGridView_RowEditing"
            OnRowUpdating="ProtuctTypesGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ProtuctTypesGridView_PageIndexChanging"
            Caption="Protuct types" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="Features" HeaderText="Features" SortExpression="Features" />
            </Columns>
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add protuct type</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="ProtuctTypeNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Description: </span>
            <asp:TextBox ID="ProtuctTypeDescriptionTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Features: </span>
            <asp:TextBox ID="ProtuctTypeFeaturesTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddProtuctTypeButton" runat="server" Text="Add product type" OnClick="AddProtuctTypeButton_Click"/>
        </div>
    </div>
    
</asp:Content>
