<%@ Page Language="C#" Title="Products" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Products.aspx.cs" Inherits="WebApplication.Products.Products" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ProductsGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ProductsGridView_RowCancelingEdit"
            OnRowDeleting="ProductsGridView_RowDeleting"
            OnRowEditing="ProductsGridView_RowEditing"
            OnRowUpdating="ProductsGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ProductsGridView_PageIndexChanging"
            Caption="Products" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="StorageConditions" HeaderText="Storage conditions" SortExpression="StorageConditions" />
                <asp:BoundField DataField="Packaging" HeaderText="Packaging" SortExpression="Packaging" />

                <asp:TemplateField HeaderText="ExpiryDate" SortExpression="ExpiryDate">
                    <EditItemTemplate>
                        <asp:Calendar ID="ExpiryDateCalendar" runat="server" SelectedDate='<%# Bind("ExpiryDate") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ExpiryDate" runat="server" Text='<%# Eval("ExpiryDate") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />

                <asp:TemplateField HeaderText="Product type" SortExpression="ProductType.Name">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ProductTypesFieldDropDownList" DataSourceID="ProductTypesSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"  SelectedValue='<%# Bind("ProductTypeId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ProductTypeId" runat="server" Text='<%# Eval("ProductType.Name") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Manufacturer" SortExpression="Manufacturer.Name">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ManufacturersFieldDropDownList" DataSourceID="ManufacturersSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"  SelectedValue='<%# Bind("ManufacturerId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ManufacturerId" runat="server" Text='<%# Eval("Manufacturer.Name") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add product</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="ProductNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Storage conditions: </span>
            <asp:TextBox ID="ProductStorageConditionsTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Packaging: </span>
            <asp:TextBox ID="ProductPackagingTextBox" runat="server"></asp:TextBox>
        </div>  

        <div>
            <span>Expiry date: </span>
            <asp:Calendar ID="ProductExpiryDateTextBox" runat="server"></asp:Calendar>
        </div>

        <div>
            <span>Price: </span>
            <asp:TextBox ID="ProductPriceTextBox" runat="server"></asp:TextBox>
        </div> 

        <div>
            <span>Product type: </span>
            <asp:DropDownList ID="ProductTypesDropDownList" DataSourceID="ProductTypesSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"></asp:DropDownList>
        </div>

        <div>
            <span>Employee: </span>
            <asp:DropDownList ID="ManufacturersDropDownList" DataSourceID="ManufacturersSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"></asp:DropDownList>
        </div>

        <div>
            <asp:Button ID="AddProductButton" runat="server" Text="Add product" OnClick="AddProductButton_Click"/>
        </div>
    </div>
    
    <asp:SqlDataSource ID="ProductTypesSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [Id], [Name] FROM [ProductTypes]">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="ManufacturersSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [Id], [Name] FROM [Manufacturers]">
    </asp:SqlDataSource>
</asp:Content>


