<%@ Page Title="Manufacturers" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Manufacturers.aspx.cs" Inherits="WebApplication.Manufacturers.Manufacturers" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ManufacturersGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ManufacturersGridView_RowCancelingEdit"
            OnRowDeleting="ManufacturersGridView_RowDeleting"
            OnRowEditing="ManufacturersGridView_RowEditing"
            OnRowUpdating="ManufacturersGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ManufacturersGridView_PageIndexChanging"
            Caption="Protuct types" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            </Columns>
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add manufacturer</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="ManufacturerNameTextBox" runat="server"></asp:TextBox>
        </div>
 
        <div>
            <asp:Button ID="AddManufacturerButton" runat="server" Text="Add manufacturer" OnClick="AddManufacturerButton_Click"/>
        </div>
    </div>
    
</asp:Content>
